const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const binary=process.env.CHROMIUM_MODULE ? require(process.env.CHROMIUM_MODULE) : null;
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{try{const f=path.join(process.cwd(),'dist',req.url==='/'?'index.html':req.url);res.setHeader('Content-Type',mime[path.extname(f)]||'application/json');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(4185,'127.0.0.1',r));const browser=await chromium.launch({executablePath:binary ? await binary.executablePath() : process.env.CHROMIUM_EXECUTABLE,args:binary ? binary.args : ['--no-sandbox']});try{
const p=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4185');const nav=()=>p.locator('header nav').getByRole('button',{name:'Espacios',exact:true}).click();await nav();const w=p.getByRole('region',{name:'Protocolo guiado del estado inicial'}),btn=name=>w.getByRole('button',{name,exact:true}),data=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')));
assert(await btn('Continuar al instrumento').isVisible());assert(!await p.getByLabel('Figura de la sesión').isVisible());await p.getByLabel('Habitación del recorrido').fill('Oficina');await btn('Continuar al instrumento').click();
const next=btn('Continuar al punto interior');assert(await next.isDisabled());for(const [name,val]of [['Operador del protocolo','Operador de prueba'],['Modelo del protocolo','BG16'],['Ajustes del protocolo','Sin accesorios'],['Referencia del protocolo','Referencia A'],['Control del protocolo','Control B'],['Condiciones del protocolo','Ventana cerrada'],['Dispositivos existentes del protocolo','Ninguno']])await p.getByLabel(name,{exact:true}).fill(val);await p.getByLabel('Comprobación del protocolo').selectOption('Consistente');await next.click();await btn('Crear punto central').click();await p.getByLabel('Nombre del punto interior').fill('Escritorio');await p.getByLabel('X interior en metros').fill('1.5');await btn('Continuar a observaciones').click();assert(await btn('Revisar antes de guardar').isDisabled());for(let i=1;i<=3;i++){await p.getByLabel(`Movimiento ${i}`,{exact:true}).selectOption('Horario');await p.getByLabel(`Interpretación ${i}`,{exact:true}).selectOption('Observado');}await btn('Revisar antes de guardar').click();assert.match(await w.innerText(),/Referencia A/);assert.equal((await data()).baselines?.length || 0,0);await btn('Corregir observaciones').click();await p.getByLabel('Movimiento 3',{exact:true}).selectOption('Oscilación');await btn('Revisar antes de guardar').click();await btn('Guardar estado inicial').click();assert.match(await w.getByRole('status').innerText(),/guardado/);assert.equal((await data()).baselines[0].trials[2].movement,'Oscilación');
await btn('Cambiar instrumento').click();await btn('Volver al lugar').click();await p.getByLabel('Ancho del recorrido').fill('10');assert.equal((await data()).baselines[0].room.width,5);await btn('Continuar al instrumento').click();await p.getByLabel('Instrumento del protocolo').selectOption('Varillas de cobre');assert(!await p.getByLabel('Longitud del protocolo').isVisible());for(const [name,val]of [['Modelo del protocolo','Varillas en L'],['Ajustes del protocolo','Agarre y postura iguales']])await p.getByLabel(name).fill(val);await btn('Aún no hice la comprobación').click();await next.click();await btn('Continuar a observaciones').click();for(let i=1;i<=3;i++){await p.getByLabel(`Movimiento ${i}`,{exact:true}).selectOption(i===3?'Apertura':'Cruce');assert(await p.getByLabel(`Interpretación ${i}`,{exact:true}).isDisabled());assert(!await p.getByLabel(`Movimiento ${i}`,{exact:true}).locator('option').allTextContents().then(a=>a.includes('Horario')));}assert(await btn('Revisar antes de guardar').isDisabled());for(let i=1;i<=3;i++)await p.getByLabel(`Recorrido ${i}`,{exact:true}).fill(['Ida puerta-ventana','Regreso ventana-puerta','Perpendicular izquierda-derecha'][i-1]);await btn('Revisar antes de guardar').click();assert.match(await w.innerText(),/Perpendicular izquierda-derecha/);await btn('Guardar estado inicial').click();let saved=await data();assert.equal(saved.baselines.length,2);assert(saved.baselines[1].trials.every(t=>t.interpretation==='Indeterminado'));assert.equal(saved.baselines[1].preparation.quality,'Respuesta de varillas');
const event=p.waitForEvent('download');await p.getByRole('button',{name:'Exportar espacio',exact:true}).click();const d=await event,exported=JSON.parse(fs.readFileSync(await d.path(),'utf8'));assert.equal(exported.baselines.length,2);await p.reload();await nav();assert.match(await w.innerText(),/2 registros iniciales/);
const bad=structuredClone(exported);bad.baselines[1].trials[0].movement='Horario';await p.getByLabel('Importar espacio JSON').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await p.getByText('El archivo no contiene un espacio válido. Se conservó el registro actual.',{exact:true}).waitFor();assert.equal((await data()).baselines.length,2);
p.once('dialog',d=>d.accept());await p.getByLabel('Importar espacio JSON').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await p.getByText('Respaldo importado.',{exact:true}).waitFor();assert.equal((await data()).baselines.length,2);
for(const width of [320,390,768,1024,1440]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${width}`);}await p.setViewportSize({width:390,height:844});await p.screenshot({path:'../recorrido-espacios-movil.png',fullPage:true});
await p.locator('.advanced-spaces>summary').click();await p.locator('.point-list').getByRole('button',{name:'Escritorio',exact:true}).click();p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Eliminar punto',exact:true}).click();assert.equal((await data()).baselines.length,0);
const old={...exported};delete old.baselines;p.once('dialog',d=>d.accept());await p.getByLabel('Importar espacio JSON').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(old))});await p.getByText('Respaldo importado.',{exact:true}).waitFor();assert.equal((await data()).points.length,1);assert.deepEqual(errors,[]);console.log('PASS: recorrido único, revisión y corrección previa, péndulo, varillas, trayectorias obligatorias, interpretación indeterminada, plano histórico, respaldos, rechazo de movimientos incompatibles, registros antiguos y cinco anchos.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
