const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const binary=process.env.CHROMIUM_MODULE ? require(process.env.CHROMIUM_MODULE) : null;
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{try{const f=path.join(process.cwd(),'dist',req.url==='/'?'index.html':req.url);res.setHeader('Content-Type',mime[path.extname(f)]||'application/json');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(4185,'127.0.0.1',r));const browser=await chromium.launch({executablePath:binary ? await binary.executablePath() : process.env.CHROMIUM_EXECUTABLE,args:binary ? binary.args : ['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4185');await page.locator('header nav').getByRole('button',{name:'Espacios',exact:true}).click();const wizard=page.getByRole('region',{name:'Protocolo guiado del estado inicial'});
const next=wizard.getByRole('button',{name:'Continuar al punto interior'});assert(await next.isDisabled());
for(const [name,val]of [['Operador del protocolo','Operador de prueba'],['Modelo del protocolo','BG16 de prueba'],['Ajustes del protocolo','Sin diales'],['Referencia del protocolo','Referencia A'],['Control del protocolo','Referencia B'],['Condiciones del protocolo','Ventanas cerradas'],['Dispositivos existentes del protocolo','Ninguno']])await page.getByLabel(name,{exact:true}).fill(val);
await page.getByLabel('Comprobación del protocolo').selectOption('Consistente');await next.click();await wizard.getByRole('button',{name:'Crear punto central'}).click();await page.getByLabel('Nombre del punto interior').fill('Escritorio');await page.getByLabel('X interior en metros').fill('1.5');await page.getByLabel('Y interior en metros').fill('2');await wizard.getByRole('button',{name:'Continuar a observaciones'}).click();const save=wizard.getByRole('button',{name:'Guardar estado inicial'});assert(await save.isDisabled());
for(let i=1;i<=3;i++){await page.getByLabel(`Movimiento ${i}`,{exact:true}).selectOption(i===3?'Oscilación':'Horario');await page.getByLabel(`Interpretación ${i}`,{exact:true}).selectOption(i===3?'Indeterminado':'Observado');}await save.click();assert.match(await wizard.getByRole('status').innerText(),/guardado/);let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')));assert.equal(data.baselines.length,1);assert.equal(data.baselines[0].trials.length,3);assert.equal(data.baselines[0].point.x,30);assert.equal(data.baselines[0].preparation.length,'');
await page.getByLabel('Ancho del espacio',{exact:true}).fill('10');data=await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')));assert.equal(data.baselines[0].room.width,5);assert.equal(data.room.width,10);
await wizard.getByRole('button',{name:'Volver al punto'}).click();await wizard.getByRole('button',{name:'Volver a preparación'}).click();await page.getByLabel('Tipo de péndulo del protocolo').selectOption('Horizontal BioGeometry');assert.equal(await page.getByLabel('Longitud del protocolo').inputValue(),'');assert(await next.isDisabled());for(const [name,val]of [['Longitud del protocolo','6.2'],['Ajustes del protocolo','R'],['Referencia del protocolo','Papel rojo'],['Control del protocolo','Papel azul']])await page.getByLabel(name).fill(val);await page.getByLabel('Comprobación del protocolo').selectOption('Inconsistente');await next.click();await wizard.getByRole('button',{name:'Continuar a observaciones'}).click();for(let i=1;i<=3;i++){assert(await page.getByLabel(`Interpretación ${i}`,{exact:true}).isDisabled());await page.getByLabel(`Movimiento ${i}`,{exact:true}).selectOption('Horario');}await save.click();data=await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')));assert.equal(data.baselines.length,2);assert(data.baselines[1].trials.every(t=>t.interpretation==='Indeterminado'));
const event=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar espacio',exact:true}).click();const downloaded=await event;const exported=JSON.parse(fs.readFileSync(await downloaded.path(),'utf8'));assert.equal(exported.baselines.length,2);
await page.reload();await page.locator('header nav').getByRole('button',{name:'Espacios',exact:true}).click();assert.match(await wizard.innerText(),/2 registros iniciales/);
const bad=structuredClone(exported);bad.baselines[1].trials[0].interpretation='Observado';await page.getByLabel('Importar espacio JSON').setInputFiles({name:'invalid-baseline.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});await page.getByText('El archivo no contiene un espacio válido. Se conservó el registro actual.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')).baselines.length),2);
page.once('dialog',d=>d.accept());await page.getByLabel('Importar espacio JSON').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')).baselines.length),2);
for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${width}`);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/protocolo-inicial-movil.png',fullPage:true});
await page.locator('.point-list').getByRole('button',{name:'Escritorio',exact:true}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Eliminar punto',exact:true}).click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')).baselines.length),0);
const legacy={...exported};delete legacy.baselines;page.once('dialog',d=>d.accept());await page.getByLabel('Importar espacio JSON').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.locator('.point-list button').first().waitFor();assert.equal(await page.locator('.point-list button').count(),1);assert.equal(await page.getByRole('region',{name:'Ubicación del lugar',exact:true}).count(),1);assert.equal(await wizard.count(),1);assert.deepEqual(errors,[]);console.log('PASS: preparación, BG16 sin longitud obligatoria, tres repeticiones, fallo indeterminado, instantánea de plano, persistencia, exportar/importar, rechazo de datos inconsistentes, respaldo antiguo, borrado vinculado y 5 anchos.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
