const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const binary=process.env.CHROMIUM_MODULE ? require(process.env.CHROMIUM_MODULE) : null;
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'};
const server=http.createServer((req,res)=>{try{const f=path.join(process.cwd(),'dist',req.url==='/'?'index.html':req.url);res.setHeader('Content-Type',mime[path.extname(f)]||'application/json');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(4187,'127.0.0.1',r));const browser=await chromium.launch({executablePath:binary ? await binary.executablePath() : process.env.CHROMIUM_EXECUTABLE,args:binary ? binary.args : ['--no-sandbox']});try{
const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>console.error('PAGE',e.message));await p.addInitScript(()=>{for(const name of ['deviceorientation','deviceorientationabsolute'])window.addEventListener(name,e=>{if(e.isTrusted)e.stopImmediatePropagation();},true);});await p.goto('http://127.0.0.1:4187');await p.getByRole('button',{name:'Espacios',exact:true}).click();
const c=p.getByRole('region',{name:'Brújula de la habitación'}).first(),data=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('biogeometria-espacios-v1')));
assert.equal((await data()).room.heading,null);
await c.getByText('Introducir grados manualmente',{exact:true}).click();await c.getByLabel('Dirección manual de la pared').fill('360');assert(await c.getByRole('button',{name:'Guardar dirección manual'}).isDisabled());await c.getByLabel('Dirección manual de la pared').fill('90');await c.getByRole('button',{name:'Guardar dirección manual'}).click();assert.equal((await data()).room.heading,90);assert.equal((await data()).room.north,270);
await c.getByRole('button',{name:'Activar brújula'}).click();await c.getByRole('button',{name:'Detener brújula'}).waitFor();
const emit=async(obj)=>p.evaluate(v=>{const e=new Event('deviceorientation');Object.assign(e,v);window.dispatchEvent(e);},obj);
await emit({alpha:270,beta:0,gamma:0,absolute:false});assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isDisabled());
await emit({alpha:270,beta:0,gamma:0,absolute:true});await p.waitForFunction(()=>!document.querySelector('.room-compass .button.primary').disabled);assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isEnabled());await c.getByRole('button',{name:'Guardar orientación',exact:true}).click();assert.equal((await data()).room.heading,90);
await c.getByRole('button',{name:'Activar brújula'}).click();await c.getByRole('button',{name:'Detener brújula'}).waitFor();await emit({webkitCompassHeading:359,webkitCompassAccuracy:5,beta:0,gamma:0});await p.waitForFunction(()=>!document.querySelector('.room-compass .button.primary').disabled);await c.getByRole('button',{name:'Guardar orientación',exact:true}).click();assert.equal((await data()).room.heading,359);assert.equal((await data()).room.north,1);
await c.getByRole('button',{name:'Activar brújula'}).click();await c.getByRole('button',{name:'Detener brújula'}).waitFor();await emit({webkitCompassHeading:10,webkitCompassAccuracy:40,beta:0,gamma:0});assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isDisabled());await emit({webkitCompassHeading:10,beta:60,gamma:0});assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isDisabled());await c.getByRole('button',{name:'Detener brújula'}).click();await emit({webkitCompassHeading:44,beta:0,gamma:0});assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isDisabled());
await p.reload();await p.getByRole('button',{name:'Espacios',exact:true}).click();assert.equal((await data()).room.heading,359);await c.getByRole('button',{name:'No conozco la orientación'}).click();assert.equal((await data()).room.heading,null);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
await p.evaluate(()=>{DeviceOrientationEvent.requestPermission=async()=> 'denied';});await c.getByRole('button',{name:'Activar brújula'}).click();await c.getByText('Permiso no concedido. Puedes usar la entrada manual.',{exact:true}).waitFor();assert(await c.getByRole('button',{name:'Guardar orientación',exact:true}).isDisabled());
console.log('PASS: orientación manual, norte relativo, eventos absolutos y Safari simulados, rechazo de orientación relativa/inclinada/imprecisa, parada, persistencia, permiso denegado y cuatro anchos.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
