import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, Circle, Download, Grid2X2, Heart, Layers, Menu, Minus, Pause, PenLine, Play, Plus, RotateCcw, Search, ShieldCheck, SlidersHorizontal, Sparkles, X } from 'lucide-react';
import catalogue from './figures.json';
import foundations from './foundations.json';
import SpaceModule from './SpaceModule';
import './styles.css';

type Figure = typeof catalogue[number] & { refinedVector?: string; refinementStatus?: string };
type View = 'inicio' | 'atlas' | 'taller' | 'diario' | 'fuentes' | 'espacios';
type Entry = { id: string; date: string; figureId: string; minutes: number; focus: number; note: string };
type Point = { x: number; y: number };
type Stroke = { points: Point[]; width: number; color: string };
declare global { interface Window { __BIO_ASSETS__?: Record<string, string> } }
const asset = (path: string) => window.__BIO_ASSETS__?.[path] || path;
const figures = catalogue as Figure[];
const reviewed = figures.filter(f => f.status === 'revisada');
const resolveFigure = (id: string) => figures.find(f => f.id === id) || reviewed[0];
const storageKey = 'biogeometria-v1';
const navigation: { id: View; label: string; icon: typeof Circle }[] = [
  { id: 'inicio', label: 'Inicio', icon: Circle }, { id: 'atlas', label: 'Atlas de formas', icon: Grid2X2 },
  { id: 'taller', label: 'Taller', icon: PenLine }, { id: 'diario', label: 'Mi cuaderno', icon: BookOpen },
  { id: 'espacios', label: 'Espacios', icon: Grid2X2 }, { id: 'fuentes', label: 'Fuentes', icon: Layers },
];
const sourceLink = 'https://www.dropbox.com/preview/11_TECHNOLOGY_&_AI/Bio_Geometria/BIO%20GEOMETRIA%20IA/BIOGEOMETRY_SIGNATURES_%28Ibrahim_Karim%29_%28Z-Library%29.pdf';

function loadState(): { favorites: string[]; entries: Entry[] } {
  try {
    const raw = JSON.parse(localStorage.getItem(storageKey) || '{}');
    let legacy: unknown = [];
    try { legacy = JSON.parse(localStorage.getItem('biogeometry-favorites') || '[]'); } catch { /* Ignore malformed legacy state. */ }
    return {
      favorites: Array.isArray(raw.favorites) ? raw.favorites.filter((id: unknown) => typeof id === 'string' && figures.some(f => f.id === id)) : Array.isArray(legacy) ? legacy.filter((id: unknown) => figures.some(f => f.id === id)) : [],
      entries: Array.isArray(raw.entries) ? raw.entries.filter(validEntry) : [],
    };
  } catch { return { favorites: [], entries: [] }; }
}
function validEntry(e: unknown): e is Entry {
  if (!e || typeof e !== 'object') return false;
  const v = e as Entry;
  return typeof v.id === 'string' && typeof v.date === 'string' && !Number.isNaN(Date.parse(v.date)) && typeof v.figureId === 'string' && figures.some(f => f.id === v.figureId) && Number.isFinite(v.minutes) && v.minutes >= 1 && v.minutes <= 120 && Number.isInteger(v.focus) && v.focus >= 1 && v.focus <= 10 && typeof v.note === 'string' && v.note.length <= 3000;
}
function download(contents: string | Blob, name: string, type = 'application/json') {
  const url = URL.createObjectURL(contents instanceof Blob ? contents : new Blob([contents], { type }));
  const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
function FigureArt({ figure, original = false, refined = false, color = '#264e43', className = '' }: { figure: Figure; original?: boolean; refined?: boolean; color?: string; className?: string }) {
  return original ? <img className={`original-art ${className}`} src={asset(figure.image)} alt={`Recorte original: ${figure.name}`} loading="lazy" /> :
    <div role="img" aria-label={`Dibujo vectorial: ${figure.name}`} className={`figure-art ${className}`} style={{ backgroundColor: color, maskImage: `url("${asset(refined && figure.refinedVector ? figure.refinedVector : figure.vector)}")`, WebkitMaskImage: `url("${asset(refined && figure.refinedVector ? figure.refinedVector : figure.vector)}")` }} />;
}
function Mark() { return <svg viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="15" /><path d="M20 5c-12 10-12 20 0 30M20 5c12 10 12 20 0 30M5 20h30" /><circle cx="20" cy="20" r="5" /></svg>; }
function Tag({ figure }: { figure: Figure }) { return <span className={`tag ${figure.status === 'revisada' ? 'verified' : 'pending'}`} title="Estado de revisión documental, no validación terapéutica">{figure.status === 'revisada' ? <><Check size={12} /> Referencia revisada</> : 'Referencia por revisar'}</span>; }
function App() {
  const [view, setView] = useState<View>('inicio');
  const [selectedId, setSelectedId] = useState(reviewed[0].id);
  const [state, setState] = useState(loadState);
  const [toast, setToast] = useState('');
  const [storageError, setStorageError] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const selected = resolveFigure(selectedId);
  const announce = (message: string) => { setToast(message); setTimeout(() => setToast(''), 4000); };
  useEffect(() => { try { localStorage.setItem(storageKey, JSON.stringify({ version: 1, ...state })); setStorageError(false); } catch { setStorageError(true); } }, [state]);
  const navigate = (next: View) => { setView(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'instant' }); };
  const openFigure = (figure: Figure) => { setSelectedId(figure.id); navigate('taller'); };
  const toggleFavorite = (id: string) => setState(prev => ({ ...prev, favorites: prev.favorites.includes(id) ? prev.favorites.filter(x => x !== id) : [...prev.favorites, id] }));
  const saveEntry = (entry: Entry) => { setState(prev => ({ ...prev, entries: [entry, ...prev.entries] })); announce('Observación guardada en tu cuaderno.'); };
  return <div className="app">
    <header className="header"><button className="brand" onClick={() => navigate('inicio')} aria-label="BioGeometría, inicio"><Mark /><span>bio<span className="brand-light">geometría</span><small>ATLAS · ESTUDIO · PRÁCTICA</small></span></button>
      <nav aria-label="Navegación principal" className={menuOpen ? 'navigation open' : 'navigation'}>{navigation.map(n => <button key={n.id} className={view === n.id ? 'active' : ''} onClick={() => navigate(n.id)} aria-current={view === n.id ? 'page' : undefined}>{n.label}</button>)}</nav>
      <span className="header-note"><span /> Edición de estudio</span><button className="menu-button icon-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'}>{menuOpen ? <X /> : <Menu />}</button>
    </header>
    {storageError && <div className="storage-alert" role="alert">El navegador no permite guardar. Exporta tu cuaderno antes de cerrar esta página.</div>}
    <main>
      {view === 'inicio' && <Home onNavigate={navigate} onOpen={openFigure} entries={state.entries} favorites={state.favorites} />}
      {view === 'atlas' && <Atlas favorites={state.favorites} onFavorite={toggleFavorite} onOpen={openFigure} />}
      {view === 'taller' && <Workshop key={selected.id} figure={selected} onSelect={setSelectedId} onFavorite={toggleFavorite} isFavorite={state.favorites.includes(selected.id)} onSave={saveEntry} onNotice={announce} />}
      {view === 'diario' && <Journal entries={state.entries} figure={selected} onSave={saveEntry} onOpen={openFigure} onNotice={announce} onImport={entries => setState(prev => ({ ...prev, entries: [...new Map([...entries, ...prev.entries].map(e => [e.id, e])).values()].sort((a, b) => b.date.localeCompare(a.date)) }))} />}
      {view === 'espacios' && <SpaceModule onOpenFigure={id => openFigure(resolveFigure(id))} />}
      {view === 'fuentes' && <Sources />}
    </main>
    <footer><span>BioGeometría <b>—</b> una biblioteca para observar y aprender.</span><button onClick={() => navigate('fuentes')}>Método y referencias <ArrowUpRight size={14} /></button></footer>
    {toast && <div className="toast" role="status"><Check size={17} />{toast}</div>}
  </div>;
}

function Home({ onNavigate, onOpen, entries, favorites }: { onNavigate: (v: View) => void; onOpen: (f: Figure) => void; entries: Entry[]; favorites: string[] }) {
  return <div className="home">
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span /> GEOMETRÍA PARA LA ATENCIÓN</p><h1>La forma,<br />con <em>claridad.</em></h1><p className="hero-description">Explora los dibujos de Ibrahim Karim. Observa sus proporciones, practica el trazo y construye tu propio cuaderno de aprendizaje.</p><div className="hero-actions"><button className="button primary" onClick={() => onNavigate('atlas')}>Explorar el atlas <ArrowRight size={18} /></button><button className="text-button" onClick={() => onOpen(reviewed[0])}>Mi primera práctica <ArrowUpRight size={17} /></button></div><p className="quiet-note">Formas originales. Fuentes visibles. Observaciones propias.</p></div>
      <div className="hero-board"><div className="board-top"><span>ESTUDIO DE FORMA / 001</span><span className="mini-label">IBRAHIM KARIM</span></div><FigureArt figure={reviewed[0]} /><div className="board-bottom"><div><span className="eyebrow">DEL ARCHIVO ORIGINAL</span><strong>Mano · 1</strong><small>BioGeometry Signatures · PDF, página 89</small></div><button className="round-button" onClick={() => onOpen(reviewed[0])} aria-label="Abrir Mano 1 en el taller"><ArrowUpRight /></button></div></div>
    </section>
    <section className="stat-strip" aria-label="Estado de la biblioteca"><div><b>246</b><span>recortes recuperados</span></div><div><b>{reviewed.length.toString().padStart(2, '0')}</b><span>referencias revisadas</span></div><div><b>{favorites.length.toString().padStart(2, '0')}</b><span>formas guardadas</span></div><div><b>{entries.length.toString().padStart(2, '0')}</b><span>observaciones tuyas</span></div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">UN RECORRIDO SENCILLO</p><h2>De mirar a comprender.</h2></div><p>Tres herramientas, un mismo lugar.</p></div><div className="journey-grid">{[
      { number: '01', title: 'Encuentra una forma', text: 'Un atlas visual con búsqueda, favoritos y referencia documental.', icon: Grid2X2, view: 'atlas' as View },
      { number: '02', title: 'Hazla tuya', text: 'Amplía, compara y dibuja sobre una guía. Exporta o imprime a escala.', icon: PenLine, view: 'taller' as View },
      { number: '03', title: 'Observa lo que cambia', text: 'Anota la experiencia y revisa tu constancia, sin conclusiones automáticas.', icon: BookOpen, view: 'diario' as View },
    ].map(item => <button className="journey-card" key={item.number} onClick={() => onNavigate(item.view)}><div><span>{item.number}</span><item.icon size={23} strokeWidth={1.3} /></div><h3>{item.title}</h3><p>{item.text}</p><ArrowUpRight className="card-arrow" size={20} /></button>)}</div></section>
    <section className="section featured"><div className="section-heading"><div><p className="eyebrow">EMPIEZA POR AQUÍ</p><h2>Formas con referencia revisada.</h2></div><button className="text-button" onClick={() => onNavigate('atlas')}>Ver el atlas <ArrowRight size={16} /></button></div><div className="featured-grid">{[reviewed[0], reviewed[3], reviewed[4], reviewed[7]].map((f, i) => <button className="featured-card" key={f.id} onClick={() => onOpen(f)}><div className="featured-art"><span>{String(i + 1).padStart(2, '0')}</span><FigureArt figure={f} /></div><div className="featured-info"><div><small>{f.category}</small><h3>{f.name}</h3></div><ArrowUpRight size={19} /></div></button>)}</div></section>
    <section className="source-banner"><div className="source-seal"><ShieldCheck size={32} strokeWidth={1.1} /></div><div><p className="eyebrow">EL ORIGEN IMPORTA</p><h2>Cada dibujo necesita una fuente.</h2><p>Las referencias revisadas se distinguen de las asociaciones pendientes. Un dibujo documentado no demuestra un efecto sobre la salud.</p></div><button className="button secondary" onClick={() => onNavigate('fuentes')}>Conocer el método <ArrowUpRight size={16} /></button></section>
  </div>;
}

function Atlas({ favorites, onFavorite, onOpen }: { favorites: string[]; onFavorite: (id: string) => void; onOpen: (figure: Figure) => void }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('Revisadas'); const [group, setGroup] = useState('Todas'); const [limit, setLimit] = useState(24);
  const filtered = figures.filter(f => (filter === 'Archivo completo' || filter === 'Revisadas' && f.status === 'revisada' || filter === 'Favoritas' && favorites.includes(f.id)) && (group === 'Todas' || f.category === group) && `${f.name} ${f.originalTitle} ${f.page}`.toLowerCase().includes(query.toLowerCase()));
  useEffect(() => setLimit(24), [query, filter, group]);
  return <div className="page atlas-page"><div className="page-heading"><div><p className="eyebrow">LA BIBLIOTECA VISUAL</p><h1>Atlas de formas<span>.</span></h1><p>Explora el dibujo, comprueba su origen y llévalo al taller.</p></div><div className="page-counter"><strong>{filtered.length.toString().padStart(2, '0')}</strong><span>formas en esta vista</span></div></div>
    <div className="atlas-controls"><div className="segmented" aria-label="Filtrar catálogo">{['Revisadas', 'Archivo completo', 'Favoritas'].map(label => <button key={label} onClick={() => setFilter(label)} className={filter === label ? 'selected' : ''}>{label}{label === 'Favoritas' && <Heart size={14} />}</button>)}</div><label className="search-field"><Search size={18} /><input aria-label="Buscar formas" placeholder="Nombre, título original o página…" value={query} onChange={e => setQuery(e.target.value)} /></label><label className="select-field"><SlidersHorizontal size={16} /><select aria-label="Grupo del catálogo" value={group} onChange={e => setGroup(e.target.value)}><option>Todas</option>{[...new Set(figures.map(f => f.category))].sort().map(g => <option key={g}>{g}</option>)}</select></label></div>
    {filter === 'Archivo completo' && <div className="archive-note"><Layers size={18} /><p>El archivo contiene <b>245 posibles firmas y una ilustración de instrumento</b>. Los títulos pendientes son asociaciones automáticas que necesitan cotejo. Los grupos organizan títulos del libro, no recomendaciones de tratamiento.</p></div>}
    <div className="atlas-grid">{filtered.slice(0, limit).map(f => <article className="figure-card" key={f.id}><div className="figure-card-art"><button className="art-open" onClick={() => onOpen(f)} aria-label={`Abrir ${f.name}`}><FigureArt figure={f} /></button><span className="page-stamp">P. {f.page}</span><button className={`favorite-button ${favorites.includes(f.id) ? 'saved' : ''}`} onClick={() => onFavorite(f.id)} aria-label={`${favorites.includes(f.id) ? 'Quitar' : 'Guardar'} ${f.name} en favoritas`}><Heart size={18} fill={favorites.includes(f.id) ? 'currentColor' : 'none'} /></button></div><div className="figure-card-info"><Tag figure={f} /><h3>{f.name}</h3><p>{f.category}</p><button className="text-button" onClick={() => onOpen(f)}>Abrir en el taller <ArrowUpRight size={15} /></button></div></article>)}</div>
    {filtered.length === 0 && <div className="empty-state"><Search size={28} /><h2>No hay formas en esta vista.</h2><p>Prueba otro nombre o grupo. Guarda una forma con el corazón para encontrarla aquí.</p><button className="button secondary" onClick={() => { setQuery(''); setGroup('Todas'); setFilter('Revisadas'); }}>Volver a las revisadas</button></div>}
    {filtered.length > limit && <button className="button secondary load-more" onClick={() => setLimit(limit + 24)}>Mostrar 24 más <Plus size={16} /></button>}
  </div>;
}

function Workshop({ figure, onSelect, onFavorite, isFavorite, onSave, onNotice }: { figure: Figure; onSelect: (id: string) => void; onFavorite: (id: string) => void; isFavorite: boolean; onSave: (entry: Entry) => void; onNotice: (message: string) => void }) {
  const [mode, setMode] = useState<'vector' | 'original' | 'draw' | 'refined'>('vector');
  const [grid, setGrid] = useState(false); const [zoom, setZoom] = useState(1); const [inkColor, setInkColor] = useState('#264e43'); const [size, setSize] = useState(100);
  const [compare, setCompare] = useState(false);
  const [paper, setPaper] = useState<'A4' | 'Carta'>('A4');
  const [opacity, setOpacity] = useState(.22); const [strokes, setStrokes] = useState<Stroke[]>([]); const [width, setWidth] = useState(3); const [sourceOpen, setSourceOpen] = useState(false);
  const [minutes, setMinutes] = useState(3); const [remaining, setRemaining] = useState(180); const [running, setRunning] = useState(false); const [completed, setCompleted] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null); const drawingRef = useRef<Stroke | null>(null); const intervalRef = useRef<ReturnType<typeof setInterval>>();
  const vectorPath = mode === 'refined' && figure.refinedVector ? figure.refinedVector : figure.vector;
  const variantLabel = mode === 'refined' ? 'Variante de curvas · en revisión' : 'Vector documental';
  const printHeight = size * (figure.height + 28) / (figure.width + 28);
  const maxPrintHeight = paper === 'A4' ? 170 : 150;
  const printFits = printHeight <= maxPrintHeight;
  const index = reviewed.findIndex(f => f.id === figure.id);
  useEffect(() => { if (!running) return; const deadline = Date.now() + remaining * 1000; intervalRef.current = setInterval(() => { const next = Math.max(0, Math.ceil((deadline - Date.now()) / 1000)); setRemaining(next); if (next === 0) { setRunning(false); setCompleted(true); } }, 250); return () => clearInterval(intervalRef.current); }, [running]);
  useEffect(() => { renderStrokes(); }, [strokes, mode]);
  const renderStrokes = () => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext('2d'); if (!ctx) return; ctx.clearRect(0, 0, 800, 800);
    [...strokes, ...(drawingRef.current ? [drawingRef.current] : [])].forEach(stroke => { ctx.beginPath(); ctx.strokeStyle = stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; stroke.points.forEach((p, i) => i ? ctx.lineTo(p.x, p.y) : ctx.moveTo(p.x, p.y)); if (stroke.points.length === 1) { ctx.lineTo(stroke.points[0].x + .1, stroke.points[0].y + .1); } ctx.stroke(); });
  };
  const position = (e: React.PointerEvent<HTMLCanvasElement>): Point => { const rect = e.currentTarget.getBoundingClientRect(); return { x: (e.clientX - rect.left) * 800 / rect.width, y: (e.clientY - rect.top) * 800 / rect.height }; };
  const finishStroke = () => { if (drawingRef.current) { const stroke = drawingRef.current; drawingRef.current = null; setStrokes(prev => [...prev, stroke]); } };
  const exportVector = async () => { try { const text = await (await fetch(asset(vectorPath))).text(); const svg = text.replaceAll('currentColor', inkColor).replace('<svg ', `<svg width="${size}mm" height="${(size * (figure.height + 28) / (figure.width + 28)).toFixed(2)}mm" `); download(svg, `${figure.id}${mode === 'refined' ? '-curvas' : ''}-${size}mm.svg`, 'image/svg+xml'); onNotice('SVG exportado de la versión seleccionada, con sus proporciones conservadas.'); } catch { onNotice('No se pudo exportar el dibujo. Intenta de nuevo.'); } };
  const printFigure = async () => {
    if (!printFits) { onNotice('Elige un ancho menor para que esta forma quepa en la hoja seleccionada.'); return; }
    try {
      const source = await (await fetch(asset(vectorPath))).text();
      const svg = source.replaceAll('currentColor', '#111').replace('<svg ', `<svg style="display:block;width:${size}mm;height:auto;max-width:none" `);
      const win = window.open('', '_blank'); if (!win) { onNotice('Permite ventanas nuevas para abrir la hoja de impresión.'); return; }
      win.document.write(`<!doctype html><html lang="es"><head><title>Imprimir ${figure.id}</title><style>@page{size:${paper === 'A4' ? 'A4' : 'letter'};margin:18mm}body{font:12px system-ui;color:#111}h1{font-size:18px}svg{margin:10mm auto}.practice-note{border-bottom:1px solid #aaa;height:8mm}.sheet-guide{font-size:11px;line-height:1.5}.calibration{box-sizing:border-box;width:100mm;border-top:1px solid black;height:5mm;border-left:1px solid;border-right:1px solid}button{padding:10px}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Imprimir esta hoja</button><h1>${figure.name.replace(/[<>]/g, '')}</h1><p>BioGeometry Signatures · Ibrahim Karim · página PDF ${figure.page}. ${variantLabel}. Hoja ${paper}. Tamaño total: ${size} × ${printHeight.toFixed(1)} mm, incluidos márgenes del SVG.</p>${svg}<p class="sheet-guide">Observa los extremos, las curvas y los cruces. Compara tu dibujo con la fuente sin cambiar sus proporciones.</p><p>Fecha: ____________________ &nbsp; Observación:</p><div class="practice-note"></div><div class="calibration"></div><p>Esta línea debe medir 100 mm. Selecciona papel ${paper} e imprime al 100%, sin «ajustar a página». El tamaño es una elección de impresión, no una dosis.</p></body></html>`); win.document.close(); onNotice('Hoja lista. Usa la regla de 100 mm para comprobar la escala.');
    } catch { onNotice('No se pudo preparar la hoja.'); }
  };
  const exportDrawing = () => { const canvas = canvasRef.current; if (!canvas || strokes.length === 0) { onNotice('Dibuja algo antes de exportar tu trazo.'); return; } canvas.toBlob(blob => { if (blob) download(blob, `mi-trazo-${figure.id}.png`, 'image/png'); }); };
  return <div className="page workshop-page"><div className="page-heading"><div><p className="eyebrow">OBSERVAR · COMPARAR · TRAZAR</p><h1>El taller<span>.</span></h1><p>Una forma, todo el espacio para entenderla.</p></div><label className="figure-select">Cambiar forma<select aria-label="Seleccionar forma en el taller" value={figure.id} onChange={e => onSelect(e.target.value)}>{figures.map(f => <option key={f.id} value={f.id}>{f.name}{f.status !== 'revisada' ? ' · por revisar' : ''}</option>)}</select></label></div>
    <div className="workshop-layout"><section className="studio"><div className={`studio-toolbar ${figure.refinedVector ? 'has-refinement' : ''}`}><div className="segmented">{[{ id: 'vector', label: 'Limpio' }, { id: 'original', label: 'Original' }, { id: 'draw', label: 'Trazar' }, ...(figure.refinedVector ? [{ id: 'refined', label: 'Curvas' }] : [])].map(m => <button key={m.id} className={mode === m.id ? 'selected' : ''} onClick={() => setMode(m.id as typeof mode)}>{m.label}</button>)}</div><button className={`icon-button ${grid ? 'selected' : ''}`} aria-label="Mostrar cuadrícula" aria-pressed={grid} onClick={() => setGrid(!grid)}><Grid2X2 size={19} /></button><button className="icon-button" onClick={() => onFavorite(figure.id)} aria-label={isFavorite ? 'Quitar favorita' : 'Guardar favorita'}><Heart size={19} fill={isFavorite ? 'currentColor' : 'none'} /></button></div>
      <div className={`drawing-board ${grid ? 'with-grid' : ''}`}><span className="canvas-label">{mode === 'draw' ? 'TU TRAZO · GUÍA DE REFERENCIA' : mode === 'original' ? 'RECORTE DOCUMENTAL' : mode === 'refined' ? 'CURVAS BÉZIER · VARIANTE EN REVISIÓN' : 'TRAZO ORIGINAL · FONDO LIMPIO'}</span><div className="art-stage" style={{ transform: mode === 'draw' ? undefined : `scale(${zoom})`, opacity: mode === 'draw' ? opacity : 1 }}><FigureArt figure={figure} original={mode === 'original'} refined={mode === 'refined'} color={inkColor} />{mode === 'refined' && compare && <FigureArt figure={figure} color="#bd496e" className="comparison-outline" />}</div>{mode === 'draw' && <canvas ref={canvasRef} width={800} height={800} aria-label="Lienzo para trazar la figura" onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); drawingRef.current = { points: [position(e)], width, color: inkColor }; renderStrokes(); }} onPointerMove={e => { if (drawingRef.current) { drawingRef.current.points.push(position(e)); renderStrokes(); } }} onPointerUp={finishStroke} onPointerCancel={finishStroke} onLostPointerCapture={finishStroke} />}
        <div className="board-caption"><span>{figure.id.replaceAll('_', ' / ')}</span><span>Orientación conservada</span></div></div>
      <div className="studio-bottom"><div className="color-options" aria-label="Color del trazo">{['#264e43', '#1d2622', '#a56347', '#4a627d'].map(color => <button style={{ background: color }} key={color} aria-label={`Color ${color}`} aria-pressed={inkColor === color} onClick={() => setInkColor(color)}>{inkColor === color && <Check size={13} />}</button>)}</div>{mode === 'draw' ? <><label className="compact-range">Guía<input aria-label="Opacidad de la guía" type="range" min="0" max="1" step=".05" value={opacity} onChange={e => setOpacity(+e.target.value)} /></label><label className="compact-range">Pluma<input aria-label="Grosor de tu pluma" type="range" min="1" max="12" value={width} onChange={e => setWidth(+e.target.value)} /></label><button className="icon-button" aria-label="Deshacer último trazo" disabled={!strokes.length} onClick={() => setStrokes(strokes.slice(0, -1))}><RotateCcw size={18} /></button><button className="text-button" onClick={exportDrawing}>Mi PNG <Download size={15} /></button></> : <div className="zoom-controls"><button className="icon-button" aria-label="Reducir zoom" onClick={() => setZoom(Math.max(.5, zoom - .25))}><Minus size={16} /></button><span>{Math.round(zoom * 100)}%</span><button className="icon-button" aria-label="Aumentar zoom" onClick={() => setZoom(Math.min(2, zoom + .25))}><Plus size={16} /></button><button className="icon-button" aria-label="Restablecer zoom" onClick={() => setZoom(1)}><RotateCcw size={16} /></button></div>}</div>
    <div className="studio-help"><strong>{mode === 'draw' ? 'Dibuja con el dedo o con el ratón.' : mode === 'original' ? 'Compara con el recorte del libro.' : mode === 'refined' ? 'Compara las nuevas curvas.' : 'Observa la forma a tu ritmo.'}</strong><p>{mode === 'draw' ? 'Baja «Guía» a cero para ver solo tu dibujo. «Deshacer» retira el último trazo. «Mi PNG» guarda tu dibujo con fondo transparente, sin la referencia.' : mode === 'original' ? 'Usa «Cotejar con la página» para ver el contexto. Vuelve a «Limpio» para estudiar el contorno o a «Trazar» para practicar.' : mode === 'refined' ? 'Esta variante suaviza pequeños escalones del escaneo. La referencia documental sigue en «Limpio». La superposición muestra esa referencia en rosa. SVG e impresión usan la versión seleccionada.' : 'Activa la cuadrícula para comparar proporciones. El zoom amplía la vista; el ancho de impresión se elige por separado.'}</p>{mode === 'refined' && <button className="text-button" aria-pressed={compare} onClick={() => setCompare(!compare)}>{compare ? 'Ocultar superposición' : 'Superponer referencia'} <Layers size={15} /></button>}</div></section><aside className="workshop-aside"><div className="figure-details"><Tag figure={figure} /><h2>{figure.name}</h2><p className="original-title">{figure.originalTitle || 'Título pendiente de cotejo'}</p><div className="source-reference"><BookOpen size={16} /><div><strong>BioGeometry Signatures</strong><span>Ibrahim Karim · página PDF {figure.page}</span></div></div><p className="detail-note">El nombre reproduce o traduce el título del libro. No es una recomendación de tratamiento.</p><button className="text-button" onClick={() => setSourceOpen(true)}>Cotejar con la página <ArrowUpRight size={15} /></button></div>
      <div className="practice-panel"><p className="eyebrow">PRÁCTICA DE OBSERVACIÓN</p><h3>Menos prisa. Más atención.</h3><ol><li>Encuentra los extremos y las flechas.</li><li>Observa curvas, cruces y proporciones.</li><li>Traza sin corregir la forma original.</li></ol><div className="timer-row"><span className="timer">{String(Math.floor(remaining / 60)).padStart(2, '0')}<span>:</span>{String(remaining % 60).padStart(2, '0')}</span><button className="round-button" onClick={() => { if (completed) { setRemaining(minutes * 60); setCompleted(false); } setRunning(!running); }} aria-label={running ? 'Pausar práctica' : 'Iniciar práctica'}>{running ? <Pause size={19} /> : <Play size={19} />}</button></div><div className="duration-options">{[1, 3, 5].map(m => <button className={minutes === m ? 'active' : ''} key={m} onClick={() => { setMinutes(m); setRemaining(m * 60); setRunning(false); setCompleted(false); }}>{m} min</button>)}</div>{completed && <p className="timer-done"><Check size={14} /> Tiempo de observación completado.</p>}<p className="detail-note">La duración organiza tu práctica de dibujo.</p></div>
      <div className="export-panel"><h3>Llévala al papel.</h3><label>Papel<select aria-label="Formato de papel" value={paper} onChange={e => setPaper(e.target.value as typeof paper)}><option value="A4">A4 · 210 × 297 mm</option><option value="Carta">Carta · 216 × 279 mm</option></select></label><label>Ancho total del dibujo<select aria-label="Ancho de impresión" value={size} onChange={e => setSize(+e.target.value)}>{[30, 40, 50, 80, 100, 120, 150].map(s => <option key={s} value={s}>{s} mm</option>)}</select></label><p className="print-dimensions">Tamaño total: {size} × {printHeight.toFixed(1)} mm.<br />Incluye el margen blanco. Conserva las proporciones.</p>{!printFits && <p className="detail-note" role="status">Para que esta forma quepa en {paper}, elige hasta {Math.floor(maxPrintHeight * (figure.width + 28) / (figure.height + 28))} mm de ancho. El SVG admite el tamaño seleccionado.</p>}<div><button className="button secondary" onClick={exportVector}>SVG <Download size={15} /></button><button className="button primary" onClick={printFigure} disabled={!printFits}>Imprimir <ArrowUpRight size={15} /></button></div></div>
    </aside></div>
    <div className="workshop-navigation"><button className="text-button" onClick={() => onSelect(reviewed[(index <= 0 ? reviewed.length : index) - 1].id)}><ChevronLeft size={17} />Forma anterior revisada</button><button className="text-button" onClick={() => onSelect(reviewed[(index + 1) % reviewed.length].id)}>Siguiente revisada<ChevronRight size={17} /></button></div>
    <section className="quick-journal"><div><p className="eyebrow">DEJA UNA HUELLA</p><h2>¿Qué observaste?</h2><p>Una nota vale más que un porcentaje automático.</p></div><EntryForm figure={figure} onSave={onSave} defaultMinutes={minutes} /></section>
    {sourceOpen && <div className="modal-overlay" onClick={() => setSourceOpen(false)}><section className="source-modal" role="dialog" aria-modal="true" aria-label="Página documental de la figura" onClick={e => e.stopPropagation()} onKeyDown={e => {
      if (e.key === 'Escape') { setSourceOpen(false); return; }
      if (e.key === 'Tab') { const items = [...e.currentTarget.querySelectorAll<HTMLElement>('button,a[href]')]; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }
    }}><div><h2>Fuente · página PDF {figure.page}</h2><button className="icon-button" autoFocus onClick={() => setSourceOpen(false)} aria-label="Cerrar página documental"><X /></button></div><p>Comprueba el título, la orientación y el trazo con la página original.</p><img src={asset(`/source-pages/${figure.page}.webp`)} alt={`Página PDF ${figure.page} del libro BioGeometry Signatures`} /><a href={sourceLink} target="_blank" rel="noreferrer">Abrir el libro en Dropbox <ArrowUpRight size={16} /></a></section></div>}
  </div>;
}

function EntryForm({ figure, onSave, defaultMinutes = 3 }: { figure: Figure; onSave: (entry: Entry) => void; defaultMinutes?: number }) {
  const [note, setNote] = useState(''); const [focus, setFocus] = useState(5); const [minutes, setMinutes] = useState(defaultMinutes);
  return <form className="entry-form" onSubmit={e => { e.preventDefault(); if (!note.trim()) return; onSave({ id: crypto.randomUUID(), date: new Date().toISOString(), figureId: figure.id, minutes, focus, note: note.trim() }); setNote(''); }}><label>Tu observación<textarea aria-label="Tu observación" placeholder="Curvas que descubrí, dificultad del trazo, cómo fue prestar atención…" value={note} onChange={e => setNote(e.target.value)} required maxLength={3000} /></label><div className="form-row"><label>Minutos<input aria-label="Minutos observados" type="number" min="1" max="120" value={minutes} onChange={e => setMinutes(+e.target.value)} required /></label><label>Atención percibida · {focus}/10<input aria-label="Atención percibida" type="range" min="1" max="10" value={focus} onChange={e => setFocus(+e.target.value)} /></label><button className="button primary" type="submit">Guardar nota <Plus size={16} /></button></div></form>;
}

function Journal({ entries, figure, onSave, onOpen, onNotice, onImport }: { entries: Entry[]; figure: Figure; onSave: (e: Entry) => void; onOpen: (f: Figure) => void; onNotice: (m: string) => void; onImport: (e: Entry[]) => void }) {
  const [formOpen, setFormOpen] = useState(false); const [chosen, setChosen] = useState(figure.id);
  const fileRef = useRef<HTMLInputElement>(null);
  const total = entries.reduce((sum, e) => sum + e.minutes, 0);
  const days = new Set(entries.map(e => new Date(e.date).toLocaleDateString('sv-SE'))).size;
  return <div className="page journal-page"><div className="page-heading"><div><p className="eyebrow">TU EXPERIENCIA, CON TUS PALABRAS</p><h1>Mi cuaderno<span>.</span></h1><p>Un registro de observación. Una pequeña historia de aprendizaje.</p></div><button className="button primary" onClick={() => setFormOpen(!formOpen)}>Nueva observación <Plus size={17} /></button></div>
    <div className="journal-stats"><div><small>OBSERVACIONES</small><b>{entries.length.toString().padStart(2, '0')}</b></div><div><small>MINUTOS REGISTRADOS</small><b>{total.toString().padStart(2, '0')}</b></div><div><small>DÍAS CON PRÁCTICA</small><b>{days.toString().padStart(2, '0')}</b></div><div className="stats-copy"><PenLine size={23} /><p>Aquí cuentan tus anotaciones.<br />Los cambios percibidos no prueban causalidad.</p></div></div>
    {formOpen && <section className="new-entry"><label className="figure-select">Forma observada<select aria-label="Forma de la nueva observación" value={chosen} onChange={e => setChosen(e.target.value)}>{figures.map(f => <option value={f.id} key={f.id}>{f.name}</option>)}</select></label><EntryForm figure={resolveFigure(chosen)} onSave={e => { onSave(e); setFormOpen(false); }} /></section>}
    <div className="journal-tools"><p>{entries.length ? 'Tus notas, de la más reciente a la más antigua.' : 'Todavía no hay observaciones.'}</p><div><button className="text-button" onClick={() => download(JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), entries }, null, 2), 'biogeometria-cuaderno.json')}>Exportar cuaderno <Download size={15} /></button><button className="text-button" onClick={() => fileRef.current?.click()}>Importar <Plus size={15} /></button><input ref={fileRef} type="file" accept=".json,application/json" hidden aria-label="Importar cuaderno JSON" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 5_000_000) { onNotice('El archivo supera 5 MB.'); return; } try { const data = JSON.parse(await file.text()); if (data.version !== 1 || !Array.isArray(data.entries) || !data.entries.every(validEntry)) throw new Error(); onImport(data.entries); onNotice('Cuaderno importado; se conservaron también tus notas actuales.'); } catch { onNotice('El archivo no tiene el formato de cuaderno esperado.'); } e.target.value = ''; }} /></div></div>
    {entries.length === 0 ? <div className="empty-state journal-empty"><BookOpen size={34} strokeWidth={1.2} /><h2>La primera página está en blanco.</h2><p>Observa una forma y escribe lo que descubriste.<br />Tu cuaderno empieza con una nota.</p><button className="button secondary" onClick={() => onOpen(reviewed[0])}>Ir a mi primera práctica <ArrowRight size={16} /></button></div> : <div className="journal-list">{entries.map(entry => { const f = resolveFigure(entry.figureId); return <article className="journal-entry" key={entry.id}><button onClick={() => onOpen(f)} aria-label={`Abrir dibujo ${f.name}`}><FigureArt figure={f} /></button><div><small>{new Date(entry.date).toLocaleString('es-MX', { dateStyle: 'medium', timeStyle: 'short' })}</small><h3>{f.name}</h3><p>{entry.note}</p><div className="entry-meta"><span>{entry.minutes} min registrados</span><span>Atención percibida {entry.focus}/10</span></div></div></article>; })}</div>}
  </div>;
}

function Sources() {
  return <div className="page sources-page"><div className="page-heading"><div><p className="eyebrow">LA BASE DOCUMENTAL</p><h1>Forma y fundamento<span>.</span></h1><p>Una biblioteca es más útil cuando puedes comprobar lo que contiene.</p></div><ShieldCheck size={45} strokeWidth={1.1} /></div>
    <div className="source-intro"><h2>Recuperar el dibujo.<br />Conservar el contexto.</h2><div><p>Este atlas reúne recortes de <i>BioGeometry Signatures</i>, de Ibrahim Karim. Se retiró el fondo gris para hacer el trazo legible y se conservaron las proporciones, los cruces y las flechas presentes en cada recorte.</p><p>La forma limpia es una vectorización del dibujo escaneado. Las primeras nueve correspondencias entre imagen y título se cotejaron con las páginas 89 y 90 del PDF. Las restantes permanecen pendientes de revisión editorial.</p></div></div>
    <section className="source-book"><div className="book-cover"><Mark /><span>IBRAHIM KARIM</span><h3>BioGeometry<br /><em>Signatures</em></h3><small>FUENTE DOCUMENTAL DEL ATLAS</small></div><div><Tag figure={reviewed[0]} /><h2>El libro de origen.</h2><p><b>BioGeometry Signatures</b><br />Harmonizing the Body’s Subtle Energy Exchange with the Environment.</p><dl><div><dt>Autor</dt><dd>Ibrahim Karim</dd></div><div><dt>Archivo comprobado</dt><dd>PDF de 224 páginas</dd></div><div><dt>Material recuperado</dt><dd>246 recortes; incluyen una ilustración de instrumento</dd></div><div><dt>Páginas del catálogo</dt><dd>Ordinales del PDF; pueden diferir de la numeración impresa</dd></div></dl><a className="button secondary" href={sourceLink} target="_blank" rel="noreferrer">Consultar fuente en Dropbox <ArrowUpRight size={16} /></a></div></section>
    <section className="section method-section"><p className="eyebrow">CÓMO LEER ESTE ATLAS</p><div className="method-grid">{[
      { icon: Check, title: 'Referencia revisada', text: 'La imagen y su título se compararon con la página documental indicada. Este estado acredita la referencia del dibujo.' },
      { icon: Layers, title: 'Referencia por revisar', text: 'El recurso se recuperó, pero su asociación automática con un título todavía requiere cotejo. Puedes observarlo y abrir la página de origen.' },
      { icon: PenLine, title: 'Tu propia observación', text: 'Tus notas describen una experiencia personal. La aplicación no convierte esa experiencia en una afirmación de eficacia.' },
    ].map(item => <article key={item.title}><item.icon size={23} strokeWidth={1.3} /><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="foundations" aria-labelledby="foundations-title"><p className="eyebrow">BIOGEOMETRÍA Y DISEÑO SAGRADO</p><h2 id="foundations-title">Fundamentos y aplicación práctica.</h2><p className="foundations-intro">Una lectura del material aportado, con referencias y ejercicios de documentación. Cada ficha indica de dónde procede la idea y qué falta comprobar.</p>{foundations.map((item, index) => <details className="foundation-card" key={item.id} open={index === 0}><summary><span className="foundation-number">{String(index + 1).padStart(2, '0')}</span><span><small>{item.status}</small><strong>{item.title}</strong></span><ChevronRight size={18} /></summary><div className="foundation-content"><h3>Concepto y procedencia</h3><p>{item.proposal}</p><h3>Qué falta comprobar</h3><p>{item.contrast}</p><div className="foundation-practice"><h3>Ejercicio de documentación</h3><p>{item.practice}</p></div><div className="foundation-links">{item.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} <ArrowUpRight size={14} /></a>)}</div></div></details>)}</section>
    <section className="learning-notes"><p className="eyebrow">APRENDER CON CRITERIO</p><h2>Cuatro ideas para empezar.</h2><div>{[
      ['01', 'Observa antes de interpretar.', 'Describe la línea: dónde comienza, qué cruces tiene, qué proporciones se repiten y dónde están las flechas.'],
      ['02', 'Distingue propuesta y comprobación.', 'Karim propone un marco de armonización mediante formas. Documentar lo que enseña no equivale a demostrar sus afirmaciones.'],
      ['03', 'El título no es una prescripción.', 'El libro organiza dibujos con nombres de órganos o condiciones. En esta aplicación esos nombres son referencias documentales.'],
      ['04', 'Registra sin anticipar el resultado.', 'Escribe lo observado, fecha y contexto. Compara tus notas sin atribuir automáticamente los cambios a la forma.'],
    ].map(([n, title, text]) => <article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <div className="source-footnote"><Sparkles size={19} /><p>El material complementario del ZIP de fuentes contiene transcripciones, textos de libros y elaboraciones propias. Se conserva como contexto de investigación; no se usa para inventar propiedades de los dibujos.</p></div>
  </div>;
}
export default App;
