import { useEffect, useState } from 'react';
import { instruments, movements, interpretations, type Baseline, type Preparation, type Trial } from './baseline';

type Point = Baseline['point'];
type Props = { room: Baseline['room']; points: Point[]; selected: string; onSelect: (id: string) => void; onAdd: (x: number, y: number) => void; onUpdate: (patch: Partial<Point>) => void; records: Baseline[]; onSave: (record: Baseline) => boolean };
const initial: Preparation = { operator: '', instrument: 'BG16', model: '', length: '', settings: '', reference: '', control: '', check: 'No realizada', conditions: '', installed: '', quality: 'BG3' };
const newTrials = (): Trial[] => Array.from({ length: 3 }, () => ({ movement: '', interpretation: '', note: '' }));
const guidance: Record<string, string> = {
  BG16: 'La FAQ oficial lo describe como calibrado por su diseño. No aplicar los 6 o 7 cm de otros modelos. Su manejo se enseña en formación. Documenta la referencia utilizada y tu comprobación de consistencia.',
  'Horizontal BioGeometry': 'Manual oficial, pp. 15–17: inicio a 6 cm desde el cuerpo; referencia roja con ajuste R. Verificar colores de referencia y un color incorrecto. Para BG3: O, I, UV y −G. Consulta las figuras originales para los pequeños desplazamientos de los diales.',
  'Vertical BioGeometry': 'Manual oficial, pp. 17–20: inicio a 7 cm desde el cuerpo; ambos diales R sobre rojo y comprobación sobre azul. Documenta el ajuste y accesorio empleados. El sentido horario puede señalar la cualidad investigada; no significa siempre un resultado beneficioso.',
  'Neutro / IKUP': 'BioGeometry Signatures, pp. PDF 167–168: cuerda corta, oscilación adelante/atrás e incrementos pequeños para explorar la longitud personal. La respuesta del operador se registra separada de BG3.'
};
export default function GuidedBaseline({ room, points, selected, onSelect, onAdd, onUpdate, records, onSave }: Props) {
  const [step, setStep] = useState(1), [prep, setPrep] = useState<Preparation>(initial), [trials, setTrials] = useState(newTrials), [notice, setNotice] = useState('');
  const point = points.find(p => p.id === selected);
  useEffect(() => { setTrials(newTrials()); setNotice(''); }, [selected]);
  const ready = [prep.operator,prep.model,prep.settings,prep.reference,prep.control,prep.conditions,prep.installed].every(v => v.trim()) && (prep.instrument === 'BG16' || prep.length !== '');
  const prepared = ready && (prep.length === '' || Number(prep.length) >= .1 && Number(prep.length) <= 200);
  const complete = trials.every(t => t.movement && t.interpretation);
  const field = (key: keyof Preparation, value: string) => { setPrep(p => ({ ...p, [key]: value })); setNotice(''); };
  const changeInstrument = (value: string) => { setPrep(p => ({ ...p, instrument: value, length: '', settings: '', reference: '', control: '', check: 'No realizada', quality: value === 'Vertical BioGeometry' ? 'Verde negativo vertical' : value === 'Neutro / IKUP' ? 'Respuesta personal' : 'BG3' })); setTrials(newTrials()); };
  const changePoint = (id: string) => { onSelect(id); setTrials(newTrials()); setNotice(''); };
  const updateTrial = (index: number, patch: Partial<Trial>) => setTrials(previous => previous.map((t, i) => i === index ? { ...t, ...patch } : t));
  const changeCheck = (value: string) => { field('check', value); setTrials(previous => previous.map(t => ({ ...t, interpretation: value === 'Consistente' ? '' : 'Indeterminado' }))); };
  return <section className="space-card guided-baseline" aria-label="Protocolo guiado del estado inicial">
    <p className="eyebrow">PROTOCOLO DE LUGARES · V1</p><h2>Registra el estado inicial.</h2><p>Prepara el instrumento, localiza un punto y conserva tres observaciones. Las repeticiones son un control propuesto por la plataforma; no una medición automática de energía.</p>
    <ol className="guided-steps" aria-label="Pasos del protocolo">{['Preparación','Punto interior','Observaciones'].map((name, i) => <li key={name} aria-current={step === i + 1 ? 'step' : undefined}><span>{i + 1}</span>{name}</li>)}</ol>
    {step === 1 && <div><div className="space-form-grid">
      <label>Operador<input aria-label="Operador del protocolo" maxLength={2000} value={prep.operator} onChange={e => field('operator', e.target.value)} /></label>
      <label>Tipo de péndulo<select aria-label="Tipo de péndulo del protocolo" value={prep.instrument} onChange={e => changeInstrument(e.target.value)}>{instruments.map(i => <option key={i}>{i}</option>)}</select></label>
    </div><p className="guided-source">{guidance[prep.instrument]} <a href={prep.instrument === 'BG16' ? 'https://www.biogeometry.ca/biogeometry-faq' : 'https://www.biogeometry.ca/_files/ugd/35c39f_705ecd0126124ee1937ab50c560a094a.pdf'} target="_blank" rel="noreferrer">Consultar documentación oficial ↗</a></p>
    <div className="space-form-grid"><label>Modelo o identificación<input aria-label="Modelo del protocolo" value={prep.model} maxLength={2000} onChange={e => { field('model', e.target.value); field('check', 'No realizada'); }} placeholder="Instrumento utilizado" /></label><label>Longitud utilizada · cm{prep.instrument === 'BG16' && <small>Opcional; no es un ajuste universal</small>}<input aria-label="Longitud del protocolo" type="number" min=".1" max="200" step=".1" value={prep.length} onChange={e => { field('length', e.target.value); field('check', 'No realizada'); }} /></label></div>
    <label>Diales, accesorios y ajustes<input aria-label="Ajustes del protocolo" maxLength={2000} value={prep.settings} onChange={e => { field('settings', e.target.value); field('check', 'No realizada'); }} placeholder="Indica los utilizados; o sin diales ni accesorios" /></label>
    <div className="space-form-grid"><label>Referencia utilizada<input aria-label="Referencia del protocolo" maxLength={2000} value={prep.reference} onChange={e => { field('reference', e.target.value); field('check', 'No realizada'); }} placeholder="Objeto o papel de referencia y respuesta" /></label><label>Control de comparación<input aria-label="Control del protocolo" maxLength={2000} value={prep.control} onChange={e => { field('control', e.target.value); field('check', 'No realizada'); }} placeholder="Comprobación alternativa y respuesta" /></label></div>
    <label>Resultado de la comprobación<select aria-label="Comprobación del protocolo" value={prep.check} onChange={e => changeCheck(e.target.value)}><option>No realizada</option><option>Consistente</option><option>Inconsistente</option></select></label>
    <label>Condiciones del lugar<textarea aria-label="Condiciones del protocolo" maxLength={2000} value={prep.conditions} onChange={e => field('conditions', e.target.value)} placeholder="Aparatos encendidos, puertas, ventanas, posición…" /></label>
    <label>Dispositivos o figuras ya instalados<input aria-label="Dispositivos existentes del protocolo" maxLength={2000} value={prep.installed} onChange={e => field('installed', e.target.value)} placeholder="Indica cuáles y dónde; o ninguno" /></label>
    <p className="detail-note">Si ya hay un cubo instalado, el estado inicial se registra con cubo. Una comprobación inconsistente o no realizada obliga a guardar interpretaciones indeterminadas.</p>
    <button className="button primary" disabled={!prepared} onClick={() => { setStep(2); setNotice(''); }}>Continuar al punto interior</button></div>}
    {step === 2 && <div><p>Selecciona un punto existente o toca el plano para añadirlo. El GPS corresponde al inmueble; las posiciones interiores se expresan en metros desde la esquina superior izquierda.</p><div className="room-plan guided-plan" style={{ aspectRatio: `${room.width} / ${room.height}` }} onClick={e => { if (e.target !== e.currentTarget) return; const bounds = e.currentTarget.getBoundingClientRect(); onAdd((e.clientX - bounds.left) / bounds.width * 100, (e.clientY - bounds.top) / bounds.height * 100); setTrials(newTrials()); }}><span className="plan-north" style={{ transform: `rotate(${room.north}deg)` }}>↑ N</span>{points.map((p,i) => <button key={p.id} className={`plan-point ${p.id === selected ? 'selected' : ''}`} style={{ left:`${p.x}%`,top:`${p.y}%` }} aria-label={`Punto del protocolo ${p.name}`} onClick={e => { e.stopPropagation(); changePoint(p.id); }}>{i + 1}</button>)}</div>
    <button className="button secondary" onClick={() => { onAdd(50,50); setTrials(newTrials()); }}>Crear punto central</button><label>Punto de la sesión<select aria-label="Punto del protocolo" value={point ? selected : ''} onChange={e => changePoint(e.target.value)}><option value="">Selecciona un punto</option>{points.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    {point && <div className="space-form-grid"><label>Nombre del punto interior<input aria-label="Nombre del punto interior" maxLength={100} value={point.name} onChange={e => onUpdate({name:e.target.value})} /></label><label>X desde la esquina · m<input aria-label="X interior en metros" type="number" min={0} max={room.width} step=".01" value={+(point.x*room.width/100).toFixed(2)} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=0&&n<=room.width)onUpdate({x:n/room.width*100});}} /></label><label>Y desde la esquina · m<input aria-label="Y interior en metros" type="number" min={0} max={room.height} step=".01" value={+(point.y*room.height/100).toFixed(2)} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=0&&n<=room.height)onUpdate({y:n/room.height*100});}} /></label></div>}
    {point && <p className="guided-source"><strong>{point.name}</strong> · X {(point.x * room.width / 100).toFixed(2)} m · Y {(point.y * room.height / 100).toFixed(2)} m · plano {room.width} × {room.height} m.</p>}
    <div className="space-actions"><button className="button secondary" onClick={() => setStep(1)}>Volver a preparación</button><button className="button primary" disabled={!point || !point.name.trim()} onClick={() => setStep(3)}>Continuar a observaciones</button></div></div>}
    {step === 3 && <div><p><strong>{point?.name || 'Selecciona un punto'}</strong> · {prep.instrument} · cualidad investigada: {prep.quality}. Comprobación: {prep.check.toLowerCase()}.</p><p className="detail-note">Conserva los mismos ajustes y condiciones en las tres repeticiones. Elige el movimiento bruto antes de interpretarlo. El sentido del giro no identifica por sí solo una anomalía.</p>
    {trials.map((t,i) => <fieldset className="trial-card" key={i}><legend>Repetición {i + 1}</legend><div className="space-form-grid"><label>Movimiento observado<select aria-label={`Movimiento ${i + 1}`} value={t.movement} onChange={e => updateTrial(i,{movement:e.target.value})}><option value="">Selecciona</option>{movements.map(m => <option key={m}>{m}</option>)}</select></label><label>Interpretación del operador<select aria-label={`Interpretación ${i + 1}`} disabled={prep.check !== 'Consistente'} value={prep.check !== 'Consistente' ? 'Indeterminado' : t.interpretation} onChange={e => updateTrial(i,{interpretation:e.target.value})}><option value="">Selecciona</option>{interpretations.map(m => <option key={m}>{m}</option>)}</select></label></div><label>Nota de la repetición<input aria-label={`Nota ${i + 1}`} maxLength={2000} value={t.note} onChange={e => updateTrial(i,{note:e.target.value})} placeholder="Duración, cambio de movimiento o dificultad" /></label></fieldset>)}
    <div className="space-actions"><button className="button secondary" onClick={() => setStep(2)}>Volver al punto</button><button className="button primary" disabled={!point || !prepared || !(complete || prep.check !== 'Consistente' && trials.every(t => t.movement))} onClick={() => { if (!point) return; const record: Baseline = { id:crypto.randomUUID(),date:new Date().toISOString(),protocol:'lugares-v1',preparation:{...prep},point:{...point,name:point.name.trim()},room:{name:room.name.trim() || 'Mi espacio',width:room.width,height:room.height,north:room.north,...(room.location ? {location:{...room.location}} : {})},trials:trials.map(t => ({...t,interpretation:prep.check === 'Consistente' ? t.interpretation : 'Indeterminado'})) }; if(onSave(record)){ setTrials(newTrials()); setNotice('Estado inicial guardado. Se incluye en Exportar espacio.'); } else setNotice('No se pudo guardar. Revisa los datos o el límite de registros.'); }}>Guardar estado inicial</button></div></div>}
    {notice && <p role="status" className="space-notice">{notice}</p>}
    {records.length > 0 && <details className="baseline-history"><summary>{records.length} registros iniciales guardados</summary>{[...records].reverse().map(r => <article className="comparison-record" key={r.id}><strong>{r.point.name}</strong><p>{new Date(r.date).toLocaleString('es-MX')} · {r.preparation.operator} · {r.preparation.instrument}<br />{r.preparation.quality} · comprobación {r.preparation.check.toLowerCase()}<br />X {(r.point.x*r.room.width/100).toFixed(2)} m · Y {(r.point.y*r.room.height/100).toFixed(2)} m · {r.room.name}</p><p className="detail-note">Modelo: {r.preparation.model} · longitud: {r.preparation.length || 'No indicada'} cm<br />Ajustes: {r.preparation.settings}<br />Referencia: {r.preparation.reference}<br />Control: {r.preparation.control}<br />Condiciones: {r.preparation.conditions}<br />Instalados: {r.preparation.installed}</p><ol>{r.trials.map((t,i)=><li key={i}>{t.movement} → {t.interpretation}{t.note && ` · ${t.note}`}</li>)}</ol></article>)}</details>}
    <p className="detail-note">Registros locales con respaldo JSON. Este flujo documenta observaciones del operador; no certifica detección de BG3 ni reparación del lugar.</p>
  </section>;
}
