import RoomCompass, { northAngle } from './RoomCompass';
import { useEffect, useState } from 'react';
import SpaceLocation from './SpaceLocation';
import { instruments, movements, rodMovements, interpretations, type Baseline, type Preparation, type Trial } from './baseline';

type Point = Baseline['point'];
type Props = { room: Baseline['room']; points: Point[]; selected: string; onSelect: (id: string) => void; onAdd: (x: number, y: number) => void; onUpdate: (patch: Partial<Point>) => void; onRoom: (patch: Partial<Baseline['room']>) => void; onDelete: () => void; records: Baseline[]; onSave: (record: Baseline) => boolean };
const initial: Preparation = { operator: '', instrument: 'BG16', model: '', length: '', settings: '', reference: '', control: '', check: 'No realizada', conditions: '', installed: '', quality: 'BG3' };
const newTrials = (): Trial[] => Array.from({ length: 3 }, () => ({ movement: '', interpretation: '', note: '' }));
const guidance: Record<string, string> = {
  BG16: 'La FAQ oficial lo describe como calibrado por su diseño. No aplicar los 6 o 7 cm de otros modelos. Su manejo se enseña en formación. Documenta la referencia utilizada y tu comprobación de consistencia.',
  'Horizontal BioGeometry': 'Manual oficial, pp. 15–17: inicio a 6 cm desde el cuerpo; referencia roja con ajuste R. Verificar colores de referencia y un color incorrecto. Para BG3: O, I, UV y −G. Consulta las figuras originales para los pequeños desplazamientos de los diales.',
  'Vertical BioGeometry': 'Manual oficial, pp. 17–20: inicio a 7 cm desde el cuerpo; ambos diales R sobre rojo y comprobación sobre azul. Documenta el ajuste y accesorio empleados. El sentido horario puede señalar la cualidad investigada; no significa siempre un resultado beneficioso.',
  'Varillas de cobre': 'En este flujo las varillas registran cruces, aperturas o ausencia de cambio. Recorre una trayectoria, vuelve en sentido contrario y prueba otra perpendicular. Describe cada recorrido y conserva el mismo agarre y postura. Un cruce no confirma una línea energética. Este control de repetición es una propuesta de registro, no una calibración física.',
  'Neutro / IKUP': 'BioGeometry Signatures, pp. PDF 167–168: cuerda corta, oscilación adelante/atrás e incrementos pequeños para explorar la longitud personal. La respuesta del operador se registra separada de BG3.'
};
export default function GuidedBaseline({ room, points, selected, onSelect, onAdd, onUpdate, onRoom, onDelete, records, onSave }: Props) {
  const [step, setStep] = useState(0), [prep, setPrep] = useState<Preparation>(initial), [trials, setTrials] = useState(newTrials), [notice, setNotice] = useState('');
  const rods = prep.instrument === 'Varillas de cobre';
  const movementOptions = rods ? rodMovements : movements;
  const roomReady = !!room.name.trim();
  const point = points.find(p => p.id === selected);
  useEffect(() => { setTrials(newTrials()); setNotice(''); }, [selected, point?.x, point?.y, room.width, room.height, room.north, room.heading]);
  const ready = [prep.operator,prep.model,prep.settings,prep.reference,prep.control,prep.conditions,prep.installed].every(v => v.trim()) && (['BG16', 'Varillas de cobre'].includes(prep.instrument) || prep.length !== '');
  const prepared = ready && (prep.length === '' || Number(prep.length) >= .1 && Number(prep.length) <= 200);
  const complete = trials.every(t => t.movement && (prep.check !== 'Consistente' || t.interpretation) && (!rods || t.route?.trim()));
  const field = (key: keyof Preparation, value: string) => { setPrep(p => ({ ...p, [key]: value })); setNotice(''); };
  const changeInstrument = (value: string) => { setPrep(p => ({ ...p, instrument: value, length: '', settings: '', reference: '', control: '', check: 'No realizada', quality: value === 'Varillas de cobre' ? 'Respuesta de varillas' : value === 'Vertical BioGeometry' ? 'Verde negativo vertical' : value === 'Neutro / IKUP' ? 'Respuesta personal' : 'BG3' })); setTrials(newTrials()); };
  const changePoint = (id: string) => { onSelect(id); setTrials(newTrials()); setNotice(''); };
  const updateTrial = (index: number, patch: Partial<Trial>) => setTrials(previous => previous.map((t, i) => i === index ? { ...t, ...patch } : t));
  const changeCheck = (value: string) => { field('check', value); setTrials(previous => previous.map(t => ({ ...t, interpretation: value === 'Consistente' ? '' : 'Indeterminado' }))); };
  return <section className="space-card guided-baseline" aria-label="Protocolo guiado del estado inicial">
    <p className="eyebrow">PROTOCOLO DE LUGARES · V1</p><h2>Empieza por tu lugar.</h2><p>Un recorrido: define la habitación, prepara el instrumento, marca un punto, observa y revisa antes de guardar. Las repeticiones son un control propuesto por la plataforma; no una medición automática de energía.</p>
    <ol className="guided-steps" aria-label="Pasos del protocolo">{['Lugar','Instrumento','Puntos','Observaciones','Revisión'].map((name, i) => <li key={name} aria-current={Math.min(step, 4) === i ? 'step' : undefined}><span>{i + 1}</span>{name}</li>)}</ol>
    {step === 0 && <div><h3>1 · Define una habitación.</h3><p>Empieza con un dormitorio o escritorio. Mide el ancho y el fondo; el GPS es opcional y sólo ubica el inmueble.</p><div className="space-form-grid"><label>Nombre de la habitación<input aria-label="Habitación del recorrido" maxLength={100} value={room.name} onChange={e => onRoom({name:e.target.value})} placeholder="Dormitorio, oficina…" /></label><label>Ancho · m<input aria-label="Ancho del recorrido" type="number" min={1} max={30} step=".1" value={room.width} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=1&&n<=30)onRoom({width:n});}} /></label><label>Fondo · m<input aria-label="Fondo del recorrido" type="number" min={1} max={30} step=".1" value={room.height} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=1&&n<=30)onRoom({height:n});}} /></label></div><RoomCompass room={room} onChange={onRoom} /><details className="guided-location"><summary>Ubicación GPS y mapa · opcional</summary><SpaceLocation location={room.location} onChange={location => onRoom({location})} /></details><button className="button primary" disabled={!roomReady} onClick={() => setStep(1)}>Continuar al instrumento</button></div>}
    {step === 1 && <div><div className="space-form-grid">
      <label>Operador<input aria-label="Operador del protocolo" maxLength={2000} value={prep.operator} onChange={e => field('operator', e.target.value)} /></label>
      <label>Instrumento que utilizarás<select aria-label="Instrumento del protocolo" value={prep.instrument} onChange={e => changeInstrument(e.target.value)}>{instruments.map(i => <option key={i}>{i}</option>)}</select></label>
    </div><p className="detail-note">Elige el instrumento real. Si aún no sabes comprobarlo, usa «No realizada»; podrás registrar movimientos con interpretación indeterminada.</p><p className="guided-source">{guidance[prep.instrument]} {!rods && <a href={prep.instrument === 'BG16' ? 'https://www.biogeometry.ca/biogeometry-faq' : 'https://www.biogeometry.ca/_files/ugd/35c39f_705ecd0126124ee1937ab50c560a094a.pdf'} target="_blank" rel="noreferrer">Consultar documentación oficial ↗</a>}</p>
    <div className="space-form-grid"><label>Modelo o identificación<input aria-label="Modelo del protocolo" value={prep.model} maxLength={2000} onChange={e => { field('model', e.target.value); field('check', 'No realizada'); }} placeholder="Instrumento utilizado" /></label>{!rods && <label>Longitud utilizada · cm{prep.instrument === 'BG16' && <small>Opcional; no es un ajuste universal</small>}<input aria-label="Longitud del protocolo" type="number" min=".1" max="200" step=".1" value={prep.length} onChange={e => { field('length', e.target.value); field('check', 'No realizada'); }} /></label>}</div>
    <label>{rods ? 'Agarre, postura y configuración' : 'Diales, accesorios y ajustes'}, accesorios y ajustes<input aria-label="Ajustes del protocolo" maxLength={2000} value={prep.settings} onChange={e => { field('settings', e.target.value); field('check', 'No realizada'); }} placeholder={rods ? 'Ejemplo: varillas en L, postura y agarre mantenidos' : 'Indica los utilizados; o sin diales ni accesorios'} /></label>
    <div className="space-form-grid"><label>{rods ? 'Primera comprobación del recorrido' : 'Referencia utilizada'}<input aria-label="Referencia del protocolo" maxLength={2000} value={prep.reference} onChange={e => { field('reference', e.target.value); field('check', 'No realizada'); }} placeholder="Objeto o papel de referencia y respuesta" /></label><label>{rods ? 'Comprobación de regreso' : 'Control de comparación'}<input aria-label="Control del protocolo" maxLength={2000} value={prep.control} onChange={e => { field('control', e.target.value); field('check', 'No realizada'); }} placeholder="Comprobación alternativa y respuesta" /></label></div>
    <button className="text-button" onClick={() => {setPrep(p => ({...p,reference:'No realizada',control:'No realizada',check:'No realizada'}));setTrials(newTrials());}}>Aún no hice la comprobación</button><label>Resultado de la comprobación<select aria-label="Comprobación del protocolo" value={prep.check} onChange={e => changeCheck(e.target.value)}><option>No realizada</option><option>Consistente</option><option>Inconsistente</option></select></label>
    <label>Condiciones del lugar<textarea aria-label="Condiciones del protocolo" maxLength={2000} value={prep.conditions} onChange={e => field('conditions', e.target.value)} placeholder="Aparatos encendidos, puertas, ventanas, posición…" /></label>
    <label>Dispositivos o figuras ya instalados<input aria-label="Dispositivos existentes del protocolo" maxLength={2000} value={prep.installed} onChange={e => field('installed', e.target.value)} placeholder="Indica cuáles y dónde; o ninguno" /></label>
    <p className="detail-note">Si ya hay un cubo instalado, el estado inicial se registra con cubo. Una comprobación inconsistente o no realizada obliga a guardar interpretaciones indeterminadas.</p>
    <p className="detail-note">Completa los campos con lo que hiciste. En referencia y control puedes escribir «No realizada»; en dispositivos, «Ninguno» cuando corresponda.</p><div className="space-actions"><button className="button secondary" onClick={() => setStep(0)}>Volver al lugar</button><button className="button primary" disabled={!prepared} onClick={() => { setStep(2); setNotice(''); }}>Continuar al punto interior</button></div></div>}
    {step === 2 && <div><p>Selecciona un punto existente o toca el plano para añadirlo. El GPS corresponde al inmueble; las posiciones interiores se expresan en metros desde la esquina superior izquierda.</p><div className="room-plan guided-plan" style={{ aspectRatio: `${room.width} / ${room.height}` }} onClick={e => { if (e.target !== e.currentTarget) return; const bounds = e.currentTarget.getBoundingClientRect(); onAdd((e.clientX - bounds.left) / bounds.width * 100, (e.clientY - bounds.top) / bounds.height * 100); setTrials(newTrials()); }}><span className="plan-north" style={{ transform: `rotate(${northAngle(room)}deg)` }}>{room.heading === null ? 'Orientación desconocida' : '↑ N'}</span>{points.map((p,i) => <button key={p.id} className={`plan-point ${p.id === selected ? 'selected' : ''}`} style={{ left:`${p.x}%`,top:`${p.y}%` }} aria-label={`Punto del protocolo ${p.name}`} onClick={e => { e.stopPropagation(); changePoint(p.id); }}>{i + 1}</button>)}</div>
    <button className="button secondary" onClick={() => { onAdd(50,50); setTrials(newTrials()); }}>Crear punto central</button><label>Punto de la sesión<select aria-label="Punto del protocolo" value={point ? selected : ''} onChange={e => changePoint(e.target.value)}><option value="">Selecciona un punto</option>{points.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    {point && <div className="space-form-grid"><label>Nombre del punto interior<input aria-label="Nombre del punto interior" maxLength={100} value={point.name} onChange={e => onUpdate({name:e.target.value})} /></label><label>X desde la esquina · m<input aria-label="X interior en metros" type="number" min={0} max={room.width} step=".01" value={+(point.x*room.width/100).toFixed(2)} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=0&&n<=room.width)onUpdate({x:n/room.width*100});}} /></label><label>Y desde la esquina · m<input aria-label="Y interior en metros" type="number" min={0} max={room.height} step=".01" value={+(point.y*room.height/100).toFixed(2)} onChange={e => {const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=0&&n<=room.height)onUpdate({y:n/room.height*100});}} /></label></div>}
    {point && <button className="text-button" onClick={onDelete}>Eliminar punto seleccionado</button>}
    {point && <p className="guided-source"><strong>{point.name}</strong> · X {(point.x * room.width / 100).toFixed(2)} m · Y {(point.y * room.height / 100).toFixed(2)} m · plano {room.width} × {room.height} m.</p>}
    <div className="space-actions"><button className="button secondary" onClick={() => setStep(1)}>Volver a preparación</button><button className="button primary" disabled={!point || !point.name.trim()} onClick={() => setStep(3)}>Continuar a observaciones</button></div></div>}
    {step === 3 && <div><h3>4 · Observa sin anticipar la causa.</h3><p><strong>{point?.name || 'Selecciona un punto'}</strong> · {prep.instrument} · cualidad investigada: {prep.quality}. Comprobación: {prep.check.toLowerCase()}.</p><p className="detail-note">Conserva los mismos ajustes y condiciones en las tres repeticiones. Elige el movimiento bruto antes de interpretarlo. Cruces, aperturas o giros no identifican por sí solos una anomalía.</p>
    {trials.map((t,i) => <fieldset className="trial-card" key={i}><legend>Repetición {i + 1}</legend><div className="space-form-grid"><label>Movimiento observado<select aria-label={`Movimiento ${i + 1}`} value={t.movement} onChange={e => updateTrial(i,{movement:e.target.value})}><option value="">Selecciona</option>{movementOptions.map(m => <option key={m}>{m}</option>)}</select></label><label>Interpretación del operador<select aria-label={`Interpretación ${i + 1}`} disabled={prep.check !== 'Consistente'} value={prep.check !== 'Consistente' ? 'Indeterminado' : t.interpretation} onChange={e => updateTrial(i,{interpretation:e.target.value})}><option value="">Selecciona</option>{interpretations.map(m => <option key={m}>{m}</option>)}</select></label></div>{rods && <label>Recorrido realizado<input aria-label={`Recorrido ${i + 1}`} maxLength={200} value={t.route || ''} onChange={e => updateTrial(i,{route:e.target.value})} placeholder={i === 0 ? 'Ida: puerta hacia ventana' : i === 1 ? 'Regreso: ventana hacia puerta' : 'Perpendicular: pared izquierda hacia derecha'} /><small>Escribe el recorrido que hiciste, no el que esperabas encontrar.</small></label>}<label>Nota de la repetición<input aria-label={`Nota ${i + 1}`} maxLength={2000} value={t.note} onChange={e => updateTrial(i,{note:e.target.value})} placeholder="Duración, cambio de movimiento o dificultad" /></label></fieldset>)}
    <div className="space-actions"><button className="button secondary" onClick={() => setStep(2)}>Volver al punto</button><button className="button primary" disabled={!point || !prepared || !complete} onClick={() => setStep(4)}>Revisar antes de guardar</button></div></div>}
    {step === 4 && <div><h3>5 · Revisa tu registro.</h3><p>Comprueba el punto, los ajustes y las tres observaciones. Si difieren, conserva esas diferencias; no selecciones sólo la respuesta que esperabas.</p><div className="guided-source"><strong>{room.name} · {point?.name}</strong><p>{prep.operator} · {prep.instrument}<br />Modelo: {prep.model}{!rods && ` · longitud: ${prep.length || 'No indicada'} cm`}<br />Ajustes: {prep.settings}<br />Referencia: {prep.reference}<br />Control: {prep.control}<br />Comprobación: {prep.check.toLowerCase()} · {prep.quality}<br />{point && `X ${(point.x*room.width/100).toFixed(2)} m · Y ${(point.y*room.height/100).toFixed(2)} m`}<br />Condiciones: {prep.conditions}<br />Dispositivos existentes: {prep.installed}</p></div><ol className="review-trials">{trials.map((t,i) => <li key={i}><strong>{t.movement || 'Sin registrar'}</strong> → {prep.check === 'Consistente' ? t.interpretation : 'Indeterminado'}{t.route && <p>Recorrido: {t.route}</p>}{t.note && <p>{t.note}</p>}</li>)}</ol><p className="detail-note">La coincidencia entre recorridos no confirma líneas energéticas ni determina qué figura aplicar.</p><div className="space-actions"><button className="button secondary" onClick={() => setStep(3)}>Corregir observaciones</button><button className="button primary" disabled={!point || !prepared || !complete} onClick={() => { if (!point) return; const record: Baseline = { id:crypto.randomUUID(),date:new Date().toISOString(),protocol:'lugares-v1',preparation:{...prep},point:{...point,name:point.name.trim()},room:{name:room.name.trim() || 'Mi espacio',width:room.width,height:room.height,north:room.north,...(room.heading !== undefined ? {heading:room.heading} : {}),...(room.location ? {location:{...room.location}} : {})},trials:trials.map(t => ({...t,interpretation:prep.check === 'Consistente' ? t.interpretation : 'Indeterminado'})) }; if(onSave(record)){ setNotice('Estado inicial guardado. Se incluye en Exportar espacio.'); setStep(5); } else setNotice('No se pudo guardar. Revisa los datos o el límite de registros.'); }}>Guardar estado inicial</button></div></div>}
    {step === 5 && <div><h3>Registro guardado.</h3><p>Puedes observar otro punto usando la misma preparación o empezar con otro instrumento. Exporta el espacio para conservar una copia fuera de este navegador.</p><div className="space-actions"><button className="button primary" onClick={() => {setTrials(newTrials());setNotice('');setStep(2);}}>Observar otro punto</button><button className="button secondary" onClick={() => {setTrials(newTrials());setNotice('');setStep(1);}}>Cambiar instrumento</button></div></div>}
    {notice && <p role="status" className="space-notice">{notice}</p>}
    {records.length > 0 && <details className="baseline-history"><summary>{records.length} registros iniciales guardados</summary>{[...records].reverse().map(r => <article className="comparison-record" key={r.id}><strong>{r.point.name}</strong><p>{new Date(r.date).toLocaleString('es-MX')} · {r.preparation.operator} · {r.preparation.instrument}<br />{r.preparation.quality} · comprobación {r.preparation.check.toLowerCase()}<br />X {(r.point.x*r.room.width/100).toFixed(2)} m · Y {(r.point.y*r.room.height/100).toFixed(2)} m · {r.room.name}</p><p className="detail-note">Modelo: {r.preparation.model} · {r.preparation.instrument === 'Varillas de cobre' ? 'Varillas: sin longitud de cuerda' : `longitud: ${r.preparation.length || 'No indicada'} cm`}<br />Ajustes: {r.preparation.settings}<br />Referencia: {r.preparation.reference}<br />Control: {r.preparation.control}<br />Condiciones: {r.preparation.conditions}<br />Instalados: {r.preparation.installed}</p><ol>{r.trials.map((t,i)=><li key={i}>{t.movement} → {t.interpretation}{t.route && ` · recorrido: ${t.route}`}{t.note && ` · ${t.note}`}</li>)}</ol></article>)}</details>}
    <p className="detail-note">Registros locales con respaldo JSON. Este flujo documenta observaciones del operador; no certifica detección de BG3 ni reparación del lugar.</p>
  </section>;
}
